config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'likes/create'
  get 'comments/create'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_posts_comments_counter

  def update_posts_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_posts_like_counter

  def update_posts_like_counter
    post.increment!(:like_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, class_name: 'Comment', dependent: :destroy
  has_many :likes, class_name: 'Like', dependent: :destroy
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :like_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_5_comment
    comments.limit(5).order(created_at: :desc)
  end

  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'author_id', dependent: :destroy
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.last_3_posts(id)
    Post.all.where("author_id = #{id}").order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @post = Post.find(params[:comment][:post_id])

    if @comment.save
      flash.notice = 'Comment was successfully created.'
      redirect_to "/users/#{@post.author_id}/posts/#{@post.id}/"
    else
      flash.alert = 'Comment was not created.'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author_id, :post_id, :text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author_id: current_user.id, post_id: @post.id)

    if @like.save
      flash.notice = 'You liked this post!'
    else
      flash.alert = 'Error liking post!'
    end
    redirect_to user_post_path(user_id: current_user.id, id: @post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @user_posts = User.last_3_posts(params[:user_id])
    @posts = @user.posts.includes(:comments, :likes)
  end

  def show
    @post = Post.includes(:comments, :likes).find(params[:id])
    @comments = @post.comments.includes(:author)
    @user = @post.author
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @user.posts_counter -= 1
    @post.destroy!
    @user.save
    redirect_to user_post_path(@user.id)
    flash[:notice] = 'Post was successfully deleted.'
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.new(post_params)

    if post.save
      flash.notice = 'Post was successfully created.'
      redirect_to user_posts_path(post.author)
    else
      flash.alert = 'Post was not created.'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_posts = User.last_3_posts(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def no_comment
    content_tag(:p, 'No comments yet.') if @comments.empty?
  end

  # def nopost_comment
  #   if @comments.empty?
  #     "No comments yet."
  #   end
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="flash-msg">
        <p><%= msg %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<%= render "users/user", locals: {user: @user } %>
<div class="user-post-bio-wrapper">
  <div class="post-new-index">
    <h2>All Posts</h2>
    <button type="button" class="user-more-posts-btn">
      <%= link_to(new_user_post_path) do %>
        <i class='bx bxs-message-add bx-sm'></i>
      <% end %>
    </button>
  </div>
  
  <div class="user-posts-wrapper">
    <% @posts.each do |post| %>
      <div class="user-post-ind-wrapper">
        <div class="post-title-area">
          <div class="user-post-title"><%= link_to "#{post.title}", user_post_path(@user.id, post.id) %></div>
          <div class="user-posts-licom-counter">
            <div class="post-comment">
              <span>💬</span>
              <small><%= "#{post.comments_counter}" %></small>
            </div>
            <div class="post-like">
              <span>👍</span>
              <small><%= "#{post.like_counter}" %></small>
            </div>
          </div>
        </div>
        <div class="post-text">
          <p><%= post.text.truncate(300) %></p>
        </div>
        <div class="post-comment-section">
          <h3 class="intermediate-heading">Comments</h3>
          <% if post.last_5_comment.empty? %>
            <small>No comments yet</small>
          <% end %>
          <% post.last_5_comment.each do |comment|%>
            <small class="post-comment-avatar">
              <div class="comment-avatar-name">
                <img src="<%= comment.author.photo %>" alt="<%= comment.author.name %>" class="comment-avatar">
                <h4><%= "#{comment.author.name}" %><h4>
              </div>
              <div class="comment-text">
                <%= "#{comment.text.truncate(100)}" %>
              </div>
            </small>
          <% end %>
        </div>
        <div class="user-more-posts post-see-more">
          <button type="button" class="user-more-posts-btn">
            <%= link_to "See more", user_post_path(@user.id, post.id) %>
          </button>
          <% if can? :destroy, post %>
            <%= button_to '🗑️', user_post_path(@user.id, post.id), :method => :delete, class: 'form-trash' %>
          <%end%>
        </div> 
      </div> 
    <% end %>
    <div class="user-more-posts">
      <button type="button" class="user-more-posts-btn">
        <%= link_to "Go back", user_path(@user.id) %>
      </button>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Posts#New</h1>

<div class="post-new">
  <%= form_with model: @post, url: "/users/#{current_user.id}/posts" do |form| %>
    <div>
      <%= form.hidden_field :author_id, value: current_user.id %>
    </div>
    <div class="form-new-title">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'new-title' %>
    </div>
    <div class="form-new-post">
      <%= form.label :text %>
      <%= form.text_area :text, size: '90x20' %>
    </div>
    <%= form.submit class: 'form-submit-comment' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Posts#Show</h1>
<div class="user-post-bio-wrapper">
  <div class="user-posts-wrapper">
    <div class="user-post-ind-wrapper">
      <div class="post-body">
        <div class="post-title-area">
          <div class="user-post-title-s">
            <h2><%= "#{@post.title} by #{@post.author.name}" %></h2>
          </div>
          <div class="user-posts-licom-counter">
            <div class="post-comment">
              <span>💬</span>
              <small><%= "#{@post.comments_counter}" %></small>
            </div>
            <div class="post-like">
              <span>👍</span>
              <small><%= "#{@post.like_counter}" %></small>
            </div>
          </div>
        </div>
        <div class="post-likes-text post-text-show">
          <p><%= @post.text %></p>
          <div class="post-likes">
            <%= form_with model: @like, url: user_post_likes_path(user_id: current_user.id, post_id: @post.id) do |form| %>
              <div>
                <%= form.hidden_field :author_id, value: current_user.id %>
              </div>
              <div>
                <%= form.hidden_field :post_id, value: @post.id %>
              </div>
              <div class="post-actions">
                <%= form.submit '👍', class: 'form-submit' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="user-post-ind-wrapper">
      <div class="post-comment-section">
        <h3 class="intermediate-heading">Comments</h3>
        <small> <%= no_comment %> </small>
        <% @post.last_5_comment.each do |comment|%>
          <small class="post-comment-avatar">
            <div class="comment-avatar-name">
              <img src="<%= comment.author.photo %>" alt="<%= comment.author.name %>" class="comment-avatar">
              <h4><%= "#{comment.author.name}" %><h4>
            </div>
            <div class="comment-text">
              <%= "#{comment.text}" %>
            </div>
          </small>
        <% end %>
      </div>
    </div>
    <div class="post-form-comment">
      <%= form_with model: @comment, url: "/users/#{current_user.id}/posts/#{@post.id}/comments", scope: :comment do |form| %>
        <div>
          <%= form.hidden_field :author_id, value: current_user.id %>
        </div>
        <div>
          <%= form.hidden_field :post_id, value: @post.id %>
        </div>
        <div class="form-textarea">
          <%= form.text_area :text, size: "60x10", placeholder: "Leave a comment" %>
        </div>
        <%= form.submit 'Comment', class: 'form-submit-comment' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_nopost.html.erb
<p>No posts yet!</p>

app/views/users/_user.html.erb
<div class="user-wrapper">
  <div class="user-ind-wrapper">
    <figure>
      <img src="<%= @user.photo %>" width="100px" height="auto" alt="<%= @user.name %>">
    </figure>
    <div class="user-name-post">
      <div class="user-name"><%= @user.name %></div>
      <div class="user-post-counter">
        <div class="user-like">
          <small class="user-like-text"><%= "#{@user.posts_counter}" %></small>
          <span class="user-like-text">Posts</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<div class="user-wrapper">
  <% @users.each do |user|%>
    <div class="user-ind-wrapper">
      <figure>
        <img src="<%= user.photo %>" width="100px" height="auto" alt="<%= user.name %>">
      </figure>
      <div class="user-name-post">
        <div class="user-name"><%= link_to "#{user.name}", user %></div>
        <div class="user-post-counter">
        <div class="user-like">
          <small class="user-like-text"><%= "#{user.posts_counter}" %></small>
          <span class="user-like-text">Posts</span>
        </div>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<%= render "user"%>
<div class="user-post-bio-wrapper">
  <div class="user-bio">
    <h2>Biography</h2>
    <p>
      <%= @user.bio %>
    </p>
  </div>
  <div class="user-post">
    <h2>Recent Posts</h2>
    <div class="user-posts-wrapper">
      <% render "nopost" if @user_posts.empty? %>
      <% @user_posts.each do |user_post| %>
        <div class="user-post-ind-wrapper">
          <div class="post-body">
            <div class="post-title-area">
              <div class="user-post-title-u"><%= link_to "#{user_post.title}", user_post_path(@user.id, user_post.id) %></div>
              <div class="user-posts-licom-counter">
                <div class="post-comment">
                  <span>💬</span>
                  <small><%= "#{user_post.comments_counter}" %></small>
                </div>
                <div class="post-like">
                  <span>👍</span>
                  <small><%= "#{user_post.like_counter}" %></small>
                </div>
              </div>
            </div>
            <div class="post-text">
              <p><%= user_post.text.truncate(300) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="user-more-posts">
      <button type="button" class="user-more-posts-btn">
        <%= link_to "See all posts", user_posts_path(@user) %>
      </button>
    </div>
  </div>
</div>